dataset_params:
  root_dir: /home/MixedDataset/
  frame_shape:  [256, 256, 3]
  id_sampling:  False
  augmentation_params:
    flip_param:
      horizontal_flip: True
      time_flip: True
    jitter_param:
      brightness: 0.1
      contrast: 0.1
      saturation: 0.1
      hue: 0.1


model_params:
  num_regions: 18
  num_channels: 3
  estimate_affine: True
  revert_axis_swap: True

  bg_predictor_params:
    block_expansion: 32
    max_features: 1024
    num_blocks: 5
    bg_type: 'affine'

  region_predictor_params:
    temperature: 0.1
    block_expansion: 32
    max_features: 1024
    scale_factor: 0.25
    num_blocks: 5
    pca_based: True
    fast_svd: False

  generator_params:
    block_expansion: 64
    max_features: 512
    num_down_blocks: 2
    num_bottleneck_blocks: 6
    skips: True
    pixelwise_flow_predictor_params:
      block_expansion: 64
      max_features: 1024
      num_blocks: 5
      scale_factor: 0.25
      use_deformed_source: True
      use_covar_heatmap: True
      estimate_occlusion_map: True

  avd_network_params:
    id_bottle_size: 64
    pose_bottle_size: 64

train_params:
  num_epochs: 100
  num_repeats: 75
  epoch_milestones: [60, 90]
  lr: 2.0e-4
  batch_size: 9
  use_sync_bn: False
  dataloader_workers: 8
  checkpoint_freq: 20
  scales: [1, 0.5, 0.25, 0.125]
  transform_params:
    sigma_affine: 0.05
    sigma_tps: 0.005
    points_tps: 5
  loss_weights:
    perceptual: [10, 10, 10, 10, 10]
    equivariance_shift: 10
    equivariance_affine: 10

train_avd_params:
  num_epochs: 100
  num_repeats: 150
  batch_size: 256
  dataloader_workers: 20
  checkpoint_freq: 50
  epoch_milestones: [20, 25]
  lr: 1.0e-3
  random_scale: 0.25
  lambda_shift: 1
  lambda_affine: 1

reconstruction_params:
  num_videos: 1000
  format: '.mp4'

animate_params:
  num_pairs: 50
  format: '.mp4'
  mode: 'avd'

visualizer_params:
  kp_size: 5
  draw_border: True
  colormap: 'gist_rainbow'
  region_bg_color: [1, 1, 1]
